FROM golang:1.14
# install python 3.8
RUN : \
    && apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        software-properties-common \
    && add-apt-repository -y ppa:deadsnakes \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        python3 python3-dev python3-pip  \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && :
# install aws cli
RUN pip3 install --upgrade setuptools && pip3 install awscli \
    && pip3 install aws-sam-cli